### ISSUE TITLE
Does not work with Redmine V4.0.6

### ISSUE THREAD

**Issue by ashrafalzyoud** [Smile-SA/redmine_smile_base#2]
rake aborted!
RM::E:P::IssuesPdfHr MISS  instance_methods  fetch_row_values  < (SM::RedmineOverride::ExportOverride::PDFOverride::IssuesPdfHelperOverride::ExtendedQueries)
/home/redmine/4.0.6/plugins/redmine_smile_base/lib/smile_redmine_export_pdf.rb:142:in `prepended'
/home/redmine/4.0.6/plugins/redmine_smile_base/init.rb:59:in `prepend'
/home/redmine/4.0.6/plugins/redmine_smile_base/init.rb:59:in `prepend_in'
/home/redmine/4.0.6/plugins/redmine_smile_base/init.rb:158:in `block in <top (required)>'
/home/redmine/4.0.6/config/environment.rb:14:in `<top (required)>'
/home/redmine/.rbenv/versions/2.5.5/bin/bundle:23:in `load'
/home/redmine/.rbenv/versions/2.5.5/bin/bundle:23:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by Utopism** [comment]
Hi @ashrafalzyoud, sorry for the late reply.
The plugin should be compatible with RM V4.0.6
Can you give me the list of the plugins that you have installed ? perhaps another one overrides this method also, and thus takes precedence on it ?
To verify that, can you make a grep inside your plugins folder (on **fetch_row_values**) to find such an override of this method ?

**Comment by Utopism** [comment]
Hi @ashrafalzyoud, as I have no news from you, I close this issue, that is probably related to another plugin overriding  fetch_row_values also.
